# Generated by Django 5.1.7 on 2026-01-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_category_alter_entry_title_entry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
